version: "3.8"
services: 
    api:
        build: .
        ports: 
            - 5000:5000
        environment: 
            MONGO_URL: mongodb://localhost:27017/blog
    db:
        image: mongo:4.0-xenial
        ports: 
            - 27017:27017
        volumes: 
            - blog:/data/db
volumes: 
    blog:
